// This file is auto-generated by @hey-api/openapi-ts

export const Body_v1_upload_file_v1_upload_postSchema = {
  properties: {
    file: {
      anyOf: [
        {
          type: 'string',
          format: 'binary',
        },
        {
          type: 'null',
        },
      ],
      title: 'File',
    },
    url: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Url',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Path',
    },
    source: {
      type: 'string',
      title: 'Source',
    },
  },
  type: 'object',
  title: 'Body_v1_upload_file_v1_upload_post',
} as const

export const CountResponseSchema = {
  properties: {
    count: {
      type: 'integer',
      title: 'Count',
    },
  },
  type: 'object',
  required: ['count'],
  title: 'CountResponse',
} as const

export const DirectorySummarySchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    path: {
      type: 'string',
      title: 'Path',
    },
    file_count: {
      type: 'integer',
      title: 'File Count',
    },
    children: {
      items: {
        $ref: '#/components/schemas/DirectorySummary',
      },
      type: 'array',
      title: 'Children',
    },
  },
  type: 'object',
  required: ['name', 'path', 'file_count'],
  title: 'DirectorySummary',
} as const

export const ExtensionCountResponseSchema = {
  properties: {
    extension: {
      type: 'string',
      title: 'Extension',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
  },
  type: 'object',
  required: ['extension', 'count'],
  title: 'ExtensionCountResponse',
} as const

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const

export const PostSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    file_path: {
      type: 'string',
      title: 'File Path',
    },
    file_name: {
      type: 'string',
      title: 'File Name',
    },
    extension: {
      type: 'string',
      title: 'Extension',
    },
    width: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Width',
    },
    height: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Height',
    },
    aspect_ratio: {
      type: 'number',
      title: 'Aspect Ratio',
    },
    score: {
      type: 'integer',
      title: 'Score',
      default: 0,
    },
    rating: {
      type: 'integer',
      title: 'Rating',
      default: 0,
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
    },
    created_at: {
      type: 'integer',
      title: 'Created At',
    },
    meta: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Meta',
    },
    md5: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Md5',
    },
    size: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Size',
    },
    source: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Source',
    },
    caption: {
      type: 'string',
      title: 'Caption',
    },
  },
  type: 'object',
  required: ['id', 'file_path', 'file_name', 'extension', 'aspect_ratio', 'meta', 'md5', 'size', 'source', 'caption'],
  title: 'Post',
} as const

export const PostBaseSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    file_path: {
      type: 'string',
      title: 'File Path',
    },
    file_name: {
      type: 'string',
      title: 'File Name',
    },
    extension: {
      type: 'string',
      title: 'Extension',
    },
    width: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Width',
    },
    height: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Height',
    },
    aspect_ratio: {
      type: 'number',
      title: 'Aspect Ratio',
    },
    score: {
      type: 'integer',
      title: 'Score',
      default: 0,
    },
    rating: {
      type: 'integer',
      title: 'Rating',
      default: 0,
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
    },
    created_at: {
      type: 'integer',
      title: 'Created At',
    },
    meta: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Meta',
    },
    md5: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Md5',
    },
    size: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Size',
    },
    source: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Source',
    },
    caption: {
      type: 'string',
      title: 'Caption',
    },
  },
  type: 'object',
  required: ['id', 'file_path', 'file_name', 'extension', 'aspect_ratio', 'meta', 'md5', 'size', 'source', 'caption'],
  title: 'PostBase',
} as const

export const PostCountResponseSchema = {
  properties: {
    count: {
      type: 'integer',
      title: 'Count',
    },
  },
  type: 'object',
  required: ['count'],
  title: 'PostCountResponse',
} as const

export const PostFilterSchema = {
  properties: {
    rating: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Rating',
      default: [],
    },
    score: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Score',
      default: [],
    },
    tags: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Tags',
      default: [],
    },
    extension: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Extension',
      default: [],
    },
    folder: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Folder',
    },
  },
  type: 'object',
  title: 'PostFilter',
} as const

export const PostHasTagPublicSchema = {
  properties: {
    is_auto: {
      type: 'boolean',
      title: 'Is Auto',
    },
    tag_info: {
      $ref: '#/components/schemas/TagPublic',
    },
  },
  type: 'object',
  required: ['is_auto', 'tag_info'],
  title: 'PostHasTagPublic',
} as const

export const PostWithTagSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    file_path: {
      type: 'string',
      title: 'File Path',
    },
    file_name: {
      type: 'string',
      title: 'File Name',
    },
    extension: {
      type: 'string',
      title: 'Extension',
    },
    width: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Width',
    },
    height: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Height',
    },
    aspect_ratio: {
      type: 'number',
      title: 'Aspect Ratio',
    },
    score: {
      type: 'integer',
      title: 'Score',
      default: 0,
    },
    rating: {
      type: 'integer',
      title: 'Rating',
      default: 0,
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
    },
    created_at: {
      type: 'integer',
      title: 'Created At',
    },
    meta: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Meta',
    },
    md5: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Md5',
    },
    size: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Size',
    },
    source: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Source',
    },
    caption: {
      type: 'string',
      title: 'Caption',
    },
    tags: {
      items: {
        $ref: '#/components/schemas/PostHasTagPublic',
      },
      type: 'array',
      title: 'Tags',
      default: [],
    },
  },
  type: 'object',
  required: ['id', 'file_path', 'file_name', 'extension', 'aspect_ratio', 'meta', 'md5', 'size', 'source', 'caption'],
  title: 'PostWithTag',
} as const

export const RatingCountResponseSchema = {
  properties: {
    rating: {
      type: 'integer',
      title: 'Rating',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
  },
  type: 'object',
  required: ['rating', 'count'],
  title: 'RatingCountResponse',
} as const

export const RatingUpdateSchema = {
  properties: {
    rating: {
      type: 'integer',
      maximum: 5,
      minimum: 0,
      title: 'Rating',
    },
  },
  type: 'object',
  required: ['rating'],
  title: 'RatingUpdate',
} as const

export const ScoreCountResponseSchema = {
  properties: {
    score: {
      type: 'integer',
      title: 'Score',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
  },
  type: 'object',
  required: ['score', 'count'],
  title: 'ScoreCountResponse',
} as const

export const ScoreUpdateSchema = {
  properties: {
    score: {
      type: 'integer',
      maximum: 5,
      minimum: 0,
      title: 'Score',
    },
  },
  type: 'object',
  required: ['score'],
  title: 'ScoreUpdate',
} as const

export const TagSchema = {
  properties: {
    count: {
      type: 'integer',
      title: 'Count',
      default: 0,
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    group_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Group Id',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'Tag',
} as const

export const TagGroupSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    color: {
      type: 'string',
      title: 'Color',
      default: '#000000',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'TagGroup',
} as const

export const TagPublicSchema = {
  properties: {
    count: {
      type: 'integer',
      title: 'Count',
      default: 0,
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    group_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Group Id',
    },
  },
  type: 'object',
  required: ['name', 'group_id'],
  title: 'TagPublic',
} as const

export const TagResponseSchema = {
  properties: {
    count: {
      type: 'integer',
      title: 'Count',
    },
    tag_info: {
      $ref: '#/components/schemas/TagPublic',
    },
  },
  type: 'object',
  required: ['count', 'tag_info'],
  title: 'TagResponse',
} as const

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const
