// This file is auto-generated by @hey-api/openapi-ts

export const $Body_v1_get_posts_v1_posts_get = {
  properties: {
    rating_list: {
      items: {
        type: 'integer',
      },
      type: 'array',
      title: 'Rating List',
    },
    score_list: {
      items: {
        type: 'integer',
      },
      type: 'array',
      title: 'Score List',
    },
    tag_list: {
      items: {
        type: 'string',
      },
      type: 'array',
      title: 'Tag List',
    },
  },
  type: 'object',
  title: 'Body_v1_get_posts_v1_posts_get',
} as const

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const

export const $Post = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    file_path: {
      type: 'string',
      title: 'File Path',
    },
    extension: {
      type: 'string',
      title: 'Extension',
    },
    width: {
      type: 'integer',
      title: 'Width',
    },
    height: {
      type: 'integer',
      title: 'Height',
    },
    aspect_ratio: {
      type: 'number',
      title: 'Aspect Ratio',
    },
    score: {
      type: 'integer',
      title: 'Score',
    },
    rating: {
      type: 'integer',
      title: 'Rating',
    },
    description: {
      type: 'string',
      title: 'Description',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
    },
    created_at: {
      type: 'integer',
      title: 'Created At',
    },
    meta: {
      type: 'string',
      title: 'Meta',
    },
    md5: {
      type: 'string',
      title: 'Md5',
    },
    size: {
      type: 'integer',
      title: 'Size',
    },
  },
  type: 'object',
  required: ['file_path', 'extension'],
  title: 'Post',
} as const

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const
