// This file is auto-generated by @hey-api/openapi-ts

import type { RootData, V1AddTagToPostData, V1AddTagToPostError, V1AddTagToPostResponse, V1CmdApplyDanbooruTagsData, V1CmdAutoCaptionData, V1CmdAutoCaptionError, V1CmdAutoCaptionResponse, V1CmdAutoTagsAllData, V1CmdAutoTagsData, V1CmdAutoTagsError, V1CmdAutoTagsResponse, V1CmdCalculateFeaturesData, V1CmdDownloadFromDanbooruData, V1CmdDownloadFromDanbooruError, V1CmdProcessPostsData, V1CmdRotateImageData, V1CmdRotateImageError, V1CmdRotateImageResponse, V1CountGroupByExtensionData, V1CountGroupByExtensionError, V1CountGroupByExtensionResponse, V1CountGroupByRatingData, V1CountGroupByRatingError, V1CountGroupByRatingResponse, V1CountGroupByScoreData, V1CountGroupByScoreError, V1CountGroupByScoreResponse, V1CreateTagData, V1CreateTagError, V1CreateTagResponse, V1DeletePostData, V1DeletePostError, V1DeleteTagData, V1DeleteTagError, V1DeleteTagResponse, V1GetFoldersData, V1GetFoldersResponse, V1GetPostByPathData, V1GetPostByPathError, V1GetPostData, V1GetPostError, V1GetPostResponse, V1GetPostsCountData, V1GetPostsCountResponse, V1GetSimilarPostsData, V1GetSimilarPostsError, V1GetSimilarPostsResponse, V1GetTagData, V1GetTagError, V1GetTagGroupsData, V1GetTagGroupsResponse, V1GetTagResponse, V1GetTagsCountData, V1GetTagsCountResponse, V1GetTagsData, V1GetTagsError, V1GetTagsResponse, V1GetThumbnailData, V1GetThumbnailError, V1ListPostsData, V1ListPostsError, V1ListPostsResponse, V1MovePostsData, V1MovePostsError, V1MovePostsResponse, V1RemoveTagFromPostData, V1RemoveTagFromPostError, V1RemoveTagFromPostResponse, V1UpdateOpenaiKeyData, V1UpdateOpenaiKeyError, V1UpdatePostCaptionData, V1UpdatePostCaptionError, V1UpdatePostCaptionResponse, V1UpdatePostRatingData, V1UpdatePostRatingError, V1UpdatePostRatingResponse, V1UpdatePostScoreData, V1UpdatePostScoreError, V1UpdatePostScoreResponse, V1UpdatePostSourceData, V1UpdatePostSourceError, V1UpdatePostSourceResponse, V1UpdateTagData, V1UpdateTagError, V1UpdateTagResponse, V1UploadFileData, V1UploadFileError } from './types.gen'
import { formDataBodySerializer, type Options } from '@hey-api/client-axios'
import { client as _heyApiClient } from './client.gen'

/**
 * V1 List Posts
 */
export function v1ListPosts<ThrowOnError extends boolean = false>(options?: Options<V1ListPostsData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<V1ListPostsResponse, V1ListPostsError, ThrowOnError>({
    url: '/v1/posts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * V1 Delete Post
 */
export function v1DeletePost<ThrowOnError extends boolean = false>(options: Options<V1DeletePostData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).delete<unknown, V1DeletePostError, ThrowOnError>({
    url: '/v1/posts/{post_id}',
    ...options,
  })
}

/**
 * V1 Get Post
 */
export function v1GetPost<ThrowOnError extends boolean = false>(options: Options<V1GetPostData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1GetPostResponse, V1GetPostError, ThrowOnError>({
    url: '/v1/posts/{post_id}',
    ...options,
  })
}

/**
 * V1 Get Posts Count
 */
export function v1GetPostsCount<ThrowOnError extends boolean = false>(options?: Options<V1GetPostsCountData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1GetPostsCountResponse, unknown, ThrowOnError>({
    url: '/v1/posts/count',
    ...options,
  })
}

/**
 * V1 Count Group By Rating
 */
export function v1CountGroupByRating<ThrowOnError extends boolean = false>(options: Options<V1CountGroupByRatingData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<V1CountGroupByRatingResponse, V1CountGroupByRatingError, ThrowOnError>({
    url: '/v1/posts/count/rating',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * V1 Count Group By Score
 */
export function v1CountGroupByScore<ThrowOnError extends boolean = false>(options: Options<V1CountGroupByScoreData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<V1CountGroupByScoreResponse, V1CountGroupByScoreError, ThrowOnError>({
    url: '/v1/posts/count/score',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * V1 Count Group By Extension
 */
export function v1CountGroupByExtension<ThrowOnError extends boolean = false>(options: Options<V1CountGroupByExtensionData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<V1CountGroupByExtensionResponse, V1CountGroupByExtensionError, ThrowOnError>({
    url: '/v1/posts/count/extension',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * V1 Update Post Score
 */
export function v1UpdatePostScore<ThrowOnError extends boolean = false>(options: Options<V1UpdatePostScoreData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).put<V1UpdatePostScoreResponse, V1UpdatePostScoreError, ThrowOnError>({
    url: '/v1/posts/{post_id}/score',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * V1 Update Post Rating
 */
export function v1UpdatePostRating<ThrowOnError extends boolean = false>(options: Options<V1UpdatePostRatingData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).put<V1UpdatePostRatingResponse, V1UpdatePostRatingError, ThrowOnError>({
    url: '/v1/posts/{post_id}/rating',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * V1 Update Post Source
 */
export function v1UpdatePostSource<ThrowOnError extends boolean = false>(options: Options<V1UpdatePostSourceData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).put<V1UpdatePostSourceResponse, V1UpdatePostSourceError, ThrowOnError>({
    url: '/v1/posts/{post_id}/source',
    ...options,
  })
}

/**
 * V1 Update Post Caption
 */
export function v1UpdatePostCaption<ThrowOnError extends boolean = false>(options: Options<V1UpdatePostCaptionData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).put<V1UpdatePostCaptionResponse, V1UpdatePostCaptionError, ThrowOnError>({
    url: '/v1/posts/{post_id}/caption',
    ...options,
  })
}

/**
 * V1 Get Similar Posts
 */
export function v1GetSimilarPosts<ThrowOnError extends boolean = false>(options: Options<V1GetSimilarPostsData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1GetSimilarPostsResponse, V1GetSimilarPostsError, ThrowOnError>({
    url: '/v1/posts/{post_id}/similar',
    ...options,
  })
}

/**
 * V1 Cmd Calculate Features
 */
export function v1CmdCalculateFeatures<ThrowOnError extends boolean = false>(options?: Options<V1CmdCalculateFeaturesData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: '/v1/cmd/posts/features',
    ...options,
  })
}

/**
 * V1 Get Post By Path
 */
export function v1GetPostByPath<ThrowOnError extends boolean = false>(options: Options<V1GetPostByPathData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<unknown, V1GetPostByPathError, ThrowOnError>({
    url: '/v1/images/{post_path}',
    ...options,
  })
}

/**
 * V1 Get Thumbnail
 */
export function v1GetThumbnail<ThrowOnError extends boolean = false>(options: Options<V1GetThumbnailData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<unknown, V1GetThumbnailError, ThrowOnError>({
    url: '/v1/thumbnails/{post_path}',
    ...options,
  })
}

/**
 * V1 Cmd Rotate Image
 */
export function v1CmdRotateImage<ThrowOnError extends boolean = false>(options: Options<V1CmdRotateImageData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).put<V1CmdRotateImageResponse, V1CmdRotateImageError, ThrowOnError>({
    url: '/v1/cmd/posts/{post_id}/rotate',
    ...options,
  })
}

/**
 * V1 Get Tags
 */
export function v1GetTags<ThrowOnError extends boolean = false>(options?: Options<V1GetTagsData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1GetTagsResponse, V1GetTagsError, ThrowOnError>({
    url: '/v1/tags',
    ...options,
  })
}

/**
 * V1 Delete Tag
 */
export function v1DeleteTag<ThrowOnError extends boolean = false>(options: Options<V1DeleteTagData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).delete<V1DeleteTagResponse, V1DeleteTagError, ThrowOnError>({
    url: '/v1/tag/{tag_name}',
    ...options,
  })
}

/**
 * V1 Create Tag
 */
export function v1CreateTag<ThrowOnError extends boolean = false>(options: Options<V1CreateTagData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<V1CreateTagResponse, V1CreateTagError, ThrowOnError>({
    url: '/v1/tag/{tag_name}',
    ...options,
  })
}

/**
 * V1 Get Tag
 */
export function v1GetTag<ThrowOnError extends boolean = false>(options: Options<V1GetTagData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1GetTagResponse, V1GetTagError, ThrowOnError>({
    url: '/v1/tags/{tag_name}',
    ...options,
  })
}

/**
 * V1 Update Tag
 */
export function v1UpdateTag<ThrowOnError extends boolean = false>(options: Options<V1UpdateTagData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).put<V1UpdateTagResponse, V1UpdateTagError, ThrowOnError>({
    url: '/v1/tags/{tag_name}',
    ...options,
  })
}

/**
 * V1 Remove Tag From Post
 */
export function v1RemoveTagFromPost<ThrowOnError extends boolean = false>(options: Options<V1RemoveTagFromPostData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).delete<V1RemoveTagFromPostResponse, V1RemoveTagFromPostError, ThrowOnError>({
    url: '/v1/posts/{post_id}/tags/{tag_name}',
    ...options,
  })
}

/**
 * V1 Add Tag To Post
 */
export function v1AddTagToPost<ThrowOnError extends boolean = false>(options: Options<V1AddTagToPostData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<V1AddTagToPostResponse, V1AddTagToPostError, ThrowOnError>({
    url: '/v1/posts/{post_id}/tags/{tag_name}',
    ...options,
  })
}

/**
 * V1 Get Tag Groups
 */
export function v1GetTagGroups<ThrowOnError extends boolean = false>(options?: Options<V1GetTagGroupsData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1GetTagGroupsResponse, unknown, ThrowOnError>({
    url: '/v1/tag-groups',
    ...options,
  })
}

/**
 * V1 Move Posts
 */
export function v1MovePosts<ThrowOnError extends boolean = false>(options: Options<V1MovePostsData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).put<V1MovePostsResponse, V1MovePostsError, ThrowOnError>({
    url: '/v1/posts/move',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * V1 Cmd Process Posts
 */
export function v1CmdProcessPosts<ThrowOnError extends boolean = false>(options?: Options<V1CmdProcessPostsData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: '/v1/cmd/process-posts',
    ...options,
  })
}

/**
 * V1 Cmd Auto Tags
 */
export function v1CmdAutoTags<ThrowOnError extends boolean = false>(options: Options<V1CmdAutoTagsData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1CmdAutoTagsResponse, V1CmdAutoTagsError, ThrowOnError>({
    url: '/v1/cmd/auto-tags/{post_id}',
    ...options,
  })
}

/**
 * V1 Cmd Auto Tags All
 */
export function v1CmdAutoTagsAll<ThrowOnError extends boolean = false>(options?: Options<V1CmdAutoTagsAllData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/v1/cmd/auto-tags',
    ...options,
  })
}

/**
 * V1 Cmd Auto Caption
 */
export function v1CmdAutoCaption<ThrowOnError extends boolean = false>(options: Options<V1CmdAutoCaptionData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1CmdAutoCaptionResponse, V1CmdAutoCaptionError, ThrowOnError>({
    url: '/v1/cmd/auto-caption/{post_id}',
    ...options,
  })
}

/**
 * V1 Get Tags Count
 */
export function v1GetTagsCount<ThrowOnError extends boolean = false>(options?: Options<V1GetTagsCountData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1GetTagsCountResponse, unknown, ThrowOnError>({
    url: '/v1/tags/count',
    ...options,
  })
}

/**
 * V1 Get Folders
 */
export function v1GetFolders<ThrowOnError extends boolean = false>(options?: Options<V1GetFoldersData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<V1GetFoldersResponse, unknown, ThrowOnError>({
    url: '/v1/folders',
    ...options,
  })
}

/**
 * V1 Upload File
 */
export function v1UploadFile<ThrowOnError extends boolean = false>(options?: Options<V1UploadFileData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<unknown, V1UploadFileError, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/v1/upload',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  })
}

/**
 * V1 Update Openai Key
 */
export function v1UpdateOpenaiKey<ThrowOnError extends boolean = false>(options: Options<V1UpdateOpenaiKeyData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<unknown, V1UpdateOpenaiKeyError, ThrowOnError>({
    url: '/v1/cmd/update-openai-key',
    ...options,
  })
}

/**
 * V1 Cmd Apply Danbooru Tags
 */
export function v1CmdApplyDanbooruTags<ThrowOnError extends boolean = false>(options?: Options<V1CmdApplyDanbooruTagsData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: '/v1/cmd/apply-danbooru-tags',
    ...options,
  })
}

/**
 * V1 Cmd Download From Danbooru
 */
export function v1CmdDownloadFromDanbooru<ThrowOnError extends boolean = false>(options: Options<V1CmdDownloadFromDanbooruData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<unknown, V1CmdDownloadFromDanbooruError, ThrowOnError>({
    url: '/v1/cmd/download-from-danbooru',
    ...options,
  })
}

/**
 * Root
 */
export function root<ThrowOnError extends boolean = false>(options?: Options<RootData, ThrowOnError>) {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/',
    ...options,
  })
}
