// This file is auto-generated by @hey-api/openapi-ts

import { type Options, createClient, createConfig, formDataBodySerializer } from '@hey-api/client-fetch'
import type { RootError, RootResponse, V1AddTagToPostData, V1AddTagToPostError, V1AddTagToPostResponse, V1CmdAutoTagsData, V1CmdAutoTagsError, V1CmdAutoTagsResponse, V1CmdProcessPostsError, V1CmdProcessPostsResponse, V1CountGroupByRatingData, V1CountGroupByRatingError, V1CountGroupByRatingResponse, V1CountGroupByScoreData, V1CountGroupByScoreError, V1CountGroupByScoreResponse, V1CreateTagData, V1CreateTagError, V1CreateTagResponse, V1DeleteTagData, V1DeleteTagError, V1DeleteTagResponse, V1GetFoldersError, V1GetFoldersResponse, V1GetPostByPathData, V1GetPostByPathError, V1GetPostByPathResponse, V1GetPostData, V1GetPostError, V1GetPostResponse, V1GetPostsCountError, V1GetPostsCountResponse, V1GetPostsData, V1GetPostsError, V1GetPostsResponse, V1GetTagData, V1GetTagError, V1GetTagResponse, V1GetTagsCountError, V1GetTagsCountResponse, V1GetTagsError, V1GetTagsResponse, V1GetThumbnailData, V1GetThumbnailError, V1GetThumbnailResponse, V1RemoveTagFromPostData, V1RemoveTagFromPostError, V1RemoveTagFromPostResponse, V1UpdatePostRatingData, V1UpdatePostRatingError, V1UpdatePostRatingResponse, V1UpdatePostScoreData, V1UpdatePostScoreError, V1UpdatePostScoreResponse, V1UpdateTagData, V1UpdateTagError, V1UpdateTagResponse, V1UploadFileData, V1UploadFileError, V1UploadFileResponse } from './types.gen'

export const client = createClient(createConfig())

/**
 * V1 Get Posts
 */
export function v1GetPosts(options?: Options<V1GetPostsData>) {
  return (options?.client ?? client).post<V1GetPostsResponse, V1GetPostsError>({
    ...options,
    url: '/v1/posts',
  })
}

/**
 * V1 Get Posts Count
 */
export function v1GetPostsCount(options?: Options) {
  return (options?.client ?? client).get<V1GetPostsCountResponse, V1GetPostsCountError>({
    ...options,
    url: '/v1/posts/count',
  })
}

/**
 * V1 Count Group By Rating
 */
export function v1CountGroupByRating(options?: Options<V1CountGroupByRatingData>) {
  return (options?.client ?? client).get<V1CountGroupByRatingResponse, V1CountGroupByRatingError>({
    ...options,
    url: '/v1/posts/count/rating',
  })
}

/**
 * V1 Count Group By Score
 */
export function v1CountGroupByScore(options?: Options<V1CountGroupByScoreData>) {
  return (options?.client ?? client).get<V1CountGroupByScoreResponse, V1CountGroupByScoreError>({
    ...options,
    url: '/v1/posts/count/score',
  })
}

/**
 * V1 Update Post Score
 */
export function v1UpdatePostScore(options: Options<V1UpdatePostScoreData>) {
  return (options?.client ?? client).put<V1UpdatePostScoreResponse, V1UpdatePostScoreError>({
    ...options,
    url: '/v1/posts/{post_id}/score',
  })
}

/**
 * V1 Update Post Rating
 */
export function v1UpdatePostRating(options: Options<V1UpdatePostRatingData>) {
  return (options?.client ?? client).put<V1UpdatePostRatingResponse, V1UpdatePostRatingError>({
    ...options,
    url: '/v1/posts/{post_id}/rating',
  })
}

/**
 * V1 Get Post
 */
export function v1GetPost(options: Options<V1GetPostData>) {
  return (options?.client ?? client).get<V1GetPostResponse, V1GetPostError>({
    ...options,
    url: '/v1/posts/{post_id}',
  })
}

/**
 * V1 Get Post By Path
 */
export function v1GetPostByPath(options: Options<V1GetPostByPathData>) {
  return (options?.client ?? client).get<V1GetPostByPathResponse, V1GetPostByPathError>({
    ...options,
    url: '/v1/images/{post_path}',
  })
}

/**
 * V1 Get Thumbnail
 */
export function v1GetThumbnail(options: Options<V1GetThumbnailData>) {
  return (options?.client ?? client).get<V1GetThumbnailResponse, V1GetThumbnailError>({
    ...options,
    url: '/v1/thumbnails/{post_path}',
  })
}

/**
 * V1 Get Tags
 */
export function v1GetTags(options?: Options) {
  return (options?.client ?? client).get<V1GetTagsResponse, V1GetTagsError>({
    ...options,
    url: '/v1/tags',
  })
}

/**
 * V1 Create Tag
 */
export function v1CreateTag(options: Options<V1CreateTagData>) {
  return (options?.client ?? client).post<V1CreateTagResponse, V1CreateTagError>({
    ...options,
    url: '/v1/tag/{tag_name}',
  })
}

/**
 * V1 Delete Tag
 */
export function v1DeleteTag(options: Options<V1DeleteTagData>) {
  return (options?.client ?? client).delete<V1DeleteTagResponse, V1DeleteTagError>({
    ...options,
    url: '/v1/tag/{tag_name}',
  })
}

/**
 * V1 Get Tag
 */
export function v1GetTag(options: Options<V1GetTagData>) {
  return (options?.client ?? client).get<V1GetTagResponse, V1GetTagError>({
    ...options,
    url: '/v1/tags/{tag_name}',
  })
}

/**
 * V1 Update Tag
 */
export function v1UpdateTag(options: Options<V1UpdateTagData>) {
  return (options?.client ?? client).put<V1UpdateTagResponse, V1UpdateTagError>({
    ...options,
    url: '/v1/tags/{tag_name}',
  })
}

/**
 * V1 Add Tag To Post
 */
export function v1AddTagToPost(options: Options<V1AddTagToPostData>) {
  return (options?.client ?? client).post<V1AddTagToPostResponse, V1AddTagToPostError>({
    ...options,
    url: '/v1/posts/{post_id}/tags/{tag_name}',
  })
}

/**
 * V1 Remove Tag From Post
 */
export function v1RemoveTagFromPost(options: Options<V1RemoveTagFromPostData>) {
  return (options?.client ?? client).delete<V1RemoveTagFromPostResponse, V1RemoveTagFromPostError>({
    ...options,
    url: '/v1/posts/{post_id}/tags/{tag_name}',
  })
}

/**
 * V1 Cmd Process Posts
 */
export function v1CmdProcessPosts(options?: Options) {
  return (options?.client ?? client).post<V1CmdProcessPostsResponse, V1CmdProcessPostsError>({
    ...options,
    url: '/v1/cmd/process-posts',
  })
}

/**
 * V1 Cmd Auto Tags
 */
export function v1CmdAutoTags(options: Options<V1CmdAutoTagsData>) {
  return (options?.client ?? client).get<V1CmdAutoTagsResponse, V1CmdAutoTagsError>({
    ...options,
    url: '/v1/cmd/auto-tags/{post_id}',
  })
}

/**
 * V1 Get Tags Count
 */
export function v1GetTagsCount(options?: Options) {
  return (options?.client ?? client).get<V1GetTagsCountResponse, V1GetTagsCountError>({
    ...options,
    url: '/v1/tags/count',
  })
}

/**
 * V1 Get Folders
 */
export function v1GetFolders(options?: Options) {
  return (options?.client ?? client).get<V1GetFoldersResponse, V1GetFoldersError>({
    ...options,
    url: '/v1/folders',
  })
}

/**
 * V1 Upload File
 */
export function v1UploadFile(options: Options<V1UploadFileData>) {
  return (options?.client ?? client).post<V1UploadFileResponse, V1UploadFileError>({
    ...options,
    ...formDataBodySerializer,
    url: '/v1/upload',
  })
}

/**
 * Root
 */
export function root(options?: Options) {
  return (options?.client ?? client).get<RootResponse, RootError>({
    ...options,
    url: '/',
  })
}
