/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoGenerateTagBtn: typeof import('./components/AutoGenerateTagBtn.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    DialogContainer: typeof import('./components/DialogContainer.vue')['default']
    FilterRow: typeof import('./components/FilterRow.vue')['default']
    FloatWindow: typeof import('./components/FloatWindow.vue')['default']
    FolderItem: typeof import('./components/FolderItem.vue')['default']
    LazyWaterfall: typeof import('./components/LazyWaterfall.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    MainSection: typeof import('./components/MainSection.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    Popover: typeof import('./components/Popover.vue')['default']
    PostDetailPanel: typeof import('./components/PostDetailPanel.vue')['default']
    PostItem: typeof import('./components/PostItem.vue')['default']
    Rating: typeof import('./components/Rating.vue')['default']
    RatingFilter: typeof import('./components/RatingFilter.vue')['default']
    RightPanel: typeof import('./components/RightPanel.vue')['default']
    ScoreFilter: typeof import('./components/ScoreFilter.vue')['default']
    ScrollArea: typeof import('./components/ScrollArea.vue')['default']
    SelectArea: typeof import('./components/SelectArea.vue')['default']
    Slider: typeof import('./components/Slider.vue')['default']
    SpecialPathList: typeof import('./components/SpecialPathList.vue')['default']
    TagSelector: typeof import('./components/TagSelector.vue')['default']
    TagSelectorWindow: typeof import('./components/TagSelectorWindow.vue')['default']
    Window: typeof import('./components/FloatWindow.vuew.vue')['default']
  }
}
