/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AspectRatio: typeof import('./components/AspectRatio.vue')['default']
    AutoGenerateCaptionBtn: typeof import('./components/AutoGenerateCaptionBtn.vue')['default']
    AutoGenerateTagBtn: typeof import('./components/AutoGenerateTagBtn.vue')['default']
    BottomBar: typeof import('./components/BottomBar.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    DialogContainer: typeof import('./components/DialogContainer.vue')['default']
    DropOverlay: typeof import('./components/DropOverlay.vue')['default']
    ExtensionFilter: typeof import('./components/ExtensionFilter.vue')['default']
    FilterRow: typeof import('./components/FilterRow.vue')['default']
    FloatWindow: typeof import('./components/FloatWindow.vue')['default']
    FolderGrid: typeof import('./components/FolderGrid.vue')['default']
    FolderItem: typeof import('./components/FolderItem.vue')['default']
    FolderSection: typeof import('./components/FolderSection.vue')['default']
    LazyWaterfall: typeof import('./components/LazyWaterfall.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    MainSection: typeof import('./components/MainSection.vue')['default']
    Popover: typeof import('./components/Popover.vue')['default']
    PostDetail: typeof import('./components/PostDetail.vue')['default']
    PostDetailPanel: typeof import('./components/PostDetailPanel.vue')['default']
    PostItem: typeof import('./components/PostItem.vue')['default']
    PostSorter: typeof import('./components/PostSorter.vue')['default']
    PostTag: typeof import('./components/PostTag.vue')['default']
    Rating: typeof import('./components/Rating.vue')['default']
    RatingFilter: typeof import('./components/RatingFilter.vue')['default']
    RightPanel: typeof import('./components/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreFilter: typeof import('./components/ScoreFilter.vue')['default']
    ScrollArea: typeof import('./components/ScrollArea.vue')['default']
    SelectArea: typeof import('./components/SelectArea.vue')['default']
    SimiarPosts: typeof import('./components/SimilarPosts.vue')['default']
    SimilarPosts: typeof import('./components/SimilarPosts.vue')['default']
    Slider: typeof import('./components/Slider.vue')['default']
    SpecialPathList: typeof import('./components/SpecialPathList.vue')['default']
    Spotlight: typeof import('./components/Spotlight.vue')['default']
    Tag: typeof import('./components/Tag.vue')['default']
    TagSelector: typeof import('./components/TagSelector.vue')['default']
    TagSelectorWindow: typeof import('./components/TagSelectorWindow.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
    ToastSystem: typeof import('./components/ToastSystem.vue')['default']
    VirtualScroll: typeof import('./components/VirtualScroll.vue')['default']
  }
}
