/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LazyWaterfall: typeof import('./components/LazyWaterfall.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    MainSection: typeof import('./components/MainSection.vue')['default']
    PostItem: typeof import('./components/PostItem.vue')['default']
    RightPanel: typeof import('./components/RightPanel.vue')['default']
    ScrollArea: typeof import('./components/ScrollArea.vue')['default']
    SelectArea: typeof import('./components/SelectArea.vue')['default']
  }
}
